### ISSUE TITLE
Trouble building for android after 1.4.0

### ISSUE THREAD

**Issue by BarrensZeppelin** [pushbots/phonegap#51] opened 2016-11-07 12:18 UTC
When building with cordova for android I get the following error message:
```
ANDROID_HOME=/home/zii/Apps/android-sdk-linux
JAVA_HOME=/usr/lib/jvm/java-8-oracle
null
org.xwalk:xwalk_core_library:20+

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find com.pushbots:pushbots-lib:3.0.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.pom
         https://repo1.maven.org/maven2/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.aar
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.pom
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.aar
         file:/home/zii/Apps/android-sdk-linux/extras/android/m2repository/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.pom
         file:/home/zii/Apps/android-sdk-linux/extras/android/m2repository/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.aar
         file:/home/zii/Apps/android-sdk-linux/extras/google/m2repository/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.pom
         file:/home/zii/Apps/android-sdk-linux/extras/google/m2repository/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.aar
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.499 secs
Error: Error code 1 for command: /home/zii/repos/Sculpto/cordova-app/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/zii/repos/Sculpto/cordova-app/platforms/android/build.gradle,-Pandroid.useDeprecatedNdk=true
```

It's like it can't find the pushbots library in the maven repository.

**Comment by hopesourav** [comment] 2016-11-08 03:13
I also had the same problem. I solved it but introduced few more 

Step 1 : Unzip and 
[pushbot.zip](https://github.com/pushbots/phonegap/files/577218/pushbot.zip)
Copy the attached file in any one of the attached file directory. I frond the file after browsing the mavel site!
Step 2 : Now on build it will throw a multiple DEX error.
Therefore we have to remove the existing 2.x.x library from platform/android/lib/  and then compile
Step 3 : Build successful.

However my app do not receive any notification henceforth and sometime it crashes. Moreover downgrading to 1.3.9 is something I am struggling with at the moment.

**Comment by amrsobhy** [comment] 2016-11-08 11:06
Looking into it

**Comment by AbdullahDiaa** [comment] 2016-11-08 11:36
@BarrensZeppelin Can you please send me your cordova version and instructions on how to reproduce it with sample project ?

**Comment by hopesourav** [comment] 2016-11-08 12:55
Hi .. I am using cordova 5.3.3 ... Its not working there :(
Do I need to update Cordova ?

**Comment by BarrensZeppelin** [comment] 2016-11-08 14:21
Same problem with this sample application: https://github.com/BarrensZeppelin/pushbotsErrorSample
Using cordova v6.4.0 and android build tools v25.0.0

From scratch:

```
cordova init sample org.example.sample sample
cd sample
cordova platform add android@5.1.1 --save
cordova plugin add pushbots-cordova-plugin --save
cordova build android --debug
```

```
~/r/S/sample (master) $ cordova build android --debug
ANDROID_HOME=/home/zii/Apps/android-sdk-linux
JAVA_HOME=/usr/lib/jvm/java-8-oracle

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.pushbots:pushbots-lib:3.0.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.pom
         https://repo1.maven.org/maven2/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.aar
         file:/home/zii/Apps/android-sdk-linux/extras/android/m2repository/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.pom
         file:/home/zii/Apps/android-sdk-linux/extras/android/m2repository/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.aar
         file:/home/zii/Apps/android-sdk-linux/extras/google/m2repository/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.pom
         file:/home/zii/Apps/android-sdk-linux/extras/google/m2repository/com/pushbots/pushbots-lib/3.0.1/pushbots-lib-3.0.1.aar
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.867 secs
Error: Error code 1 for command: /home/zii/repos/Sculpto/sample/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/zii/repos/Sculpto/sample/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
```

**Comment by hopesourav** [comment] 2016-11-15 18:22
Hi guys,

Any updates ?

Regards,
Sourav

**Comment by AbdullahDiaa** [comment] 2016-11-15 19:30
@hopesourav @BarrensZeppelin The problem was [a bug in cordova-android 5.1.1 not supporting **jcenter**](https://issues.apache.org/jira/browse/CB-11383)

Please upgrade cordova-android platform and try again.
`cordova platform update android@5.2.2`
or
`cordova platform update android@6.0.0`
The problem should be fixed with **cordova-android 5.2.0+**

Here's the [pull request](https://github.com/apache/cordova-android/pull/309/files#diff-c37e154983ced1f8b9a9fa3754f78542R25) that added **jcenter** support to cordova

**Closed as completed by AbdullahDiaa** 2016-11-15 19:30 UTC

**Comment by BarrensZeppelin** [comment] 2016-11-15 20:41
Seems to have fixed the error. Thanks. :+1:

**Comment by hopesourav** [comment] 2016-11-16 04:25
Hi All ,

Thank you so much for your quick response. 
I have successfully build the application. However, the application keeps on crashing.
I have attached the logcat snapshot of the error.

![new error](https://cloud.githubusercontent.com/assets/8762735/20334702/3bb23ad4-abe2-11e6-9239-588ab7a399c1.png)

Could pls give a quick solution or a work around ?

Regards,
Sourav

**Comment by hopesourav** [comment] 2016-11-16 11:14
http://stackoverflow.com/questions/31142325/shared-preferences-on-a-null-object-reference-android

I guess this STOF page talks about the same error. Hope this helps :)

**Comment by hopesourav** [comment] 2016-11-20 06:09
Guys  pls help !!
